### ISSUE TITLE
XEP-0412: XMPP Compliance Suites 2019

### ISSUE THREAD

**Issue by Neustradamus** [credija/opa#35]
Please add support of https://xmpp.org/extensions/xep-0412.html

**Comment by kevinfaguiar** [comment]
I will leave this as an enhancement but first the XEPs/RFCs currently supported by this project will be properly mapped in a Wiki. The XEPs not met in XEP 0412 will be analyzed to be added in the future.

**Comment by Neustradamus** [comment]
Maybe good to do not close this ticket?

**Comment by kevinfaguiar** [comment]
This issue will be closed when the wiki with the XEPs/RFCs currently supported by this project is made.

Then, you will need to verify the wiki and open an issue for a single XEPs/RFCs you want support added.

**Comment by kevinfaguiar** [comment]
Currently documented here: https://github.com/credija/opa/wiki/Features
