### ISSUE TITLE
RFCs and XEPs support page with VERSION

### ISSUE THREAD

**Issue by Neustradamus** [credija/opa#37]
It is possible to have a XEPs and RFCs support page with version?

Examples:
- https://metronome.im/supported-xeps-list
- https://dev.gajim.org/gajim/gajim/wikis/help/gajimxepsupport
- https://github.com/jappix/jappix/blob/master/PROTOCOL.md

**Comment by kevinfaguiar** [comment]
It seems to me a good enhancement to everyone who wishes to check support for specific XEPs and RFCs.

I will probably use Github Wiki to map the supported XEPs and RFCs.

**Comment by kevinfaguiar** [comment]
Currently documented here: https://github.com/credija/opa/wiki/Features
