### ISSUE TITLE
Smileys: Smooth the switching

### ISSUE THREAD

**Issue by Echolon** [credija/opa#42]
Hi,

I like the smileys changing. But I would slightly smooth it. But still it should react quickly

**Comment by kevinfaguiar** [comment]
You mean an animation? Like some fadeIn or something like that to smooth the transition?

**Comment by Echolon** [comment]
smooth transition I think

**Comment by kevinfaguiar** [comment]
I will close this issue since it is more related to another project which is a dependency of Opa (the emoji picker). I have re-created it here: https://github.com/kevinfaguiar/cool-emoji-picker/issues/7
